### ISSUE TITLE
Missing Licence

### ISSUE THREAD

**Issue by lukewar** [trevp/ref10_extract#5]
I didn't find a licence on this project. Under what licence is this code shared? Is it possible to update the project?

**Comment by trevp** [comment]
Hi, this code is ancient and obsolete (I'll delete the repo soon, since apparently it's a distraction).  You can find the latest version (copied) in 2 places, in the java there is a license:
https://github.com/WhisperSystems/curve25519-java/tree/master/android/jni/ed25519
https://github.com/WhisperSystems/libsignal-protocol-c/tree/master/src/curve25519/ed25519
