### ISSUE TITLE
Why random suffix data?

### ISSUE THREAD

**Issue by rafalsk** [trevp/ref10_extract#6]
What's the purpose of:
/* NEW: add suffix of random data */
	memmove(sm + mlen + 64, random, 64);

why don't we leave its deterministic nature?

**Comment by trevp** [comment]
Hi, this code is ancient and obsolete (I'll delete the repo soon, since apparently it's a distraction).  You can find the latest version (copied) in 2 places:
https://github.com/WhisperSystems/curve25519-java/tree/master/android/jni/ed25519
https://github.com/WhisperSystems/libsignal-protocol-c/tree/master/src/curve25519/ed25519

Your specific question might have an answer here: https://moderncrypto.org/mail-archive/curves/2017/000925.html
